services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: strategiq
      POSTGRES_PASSWORD: strategiq
      POSTGRES_DB: strategiq
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  pg-data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
