/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../types"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  CorrectiveActionArgs: { // input type
    id?: number | null; // Int
    nonConformityId?: number | null; // Int
    ownerId?: number | null; // Int
    status?: NexusGenEnums['CorrectiveActionStatus'] | null; // CorrectiveActionStatus
  }
  CorrectiveActionOrderInput: { // input type
    column: NexusGenEnums['CorrectiveActionOrderBy']; // CorrectiveActionOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  EffectivenessCheckArgs: { // input type
    correctiveActionId?: number | null; // Int
    id?: number | null; // Int
    result?: NexusGenEnums['EffectivenessResult'] | null; // EffectivenessResult
  }
  EffectivenessCheckOrderInput: { // input type
    column: NexusGenEnums['EffectivenessCheckOrderBy']; // EffectivenessCheckOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  EvidenceArgs: { // input type
    correctiveActionId?: number | null; // Int
    id?: number | null; // Int
    includeDeleted?: boolean | null; // Boolean
    indicatorId?: number | null; // Int
    initiativeId?: number | null; // Int
    nonConformityId?: number | null; // Int
    strategicObjectiveId?: number | null; // Int
  }
  IndicatorArgs: { // input type
    frequency?: NexusGenEnums['IndicatorFrequency'] | null; // IndicatorFrequency
    id?: number | null; // Int
    name?: string | null; // String
    ownerId?: number | null; // Int
  }
  IndicatorEntryArgs: { // input type
    id?: number | null; // Int
    indicatorId?: number | null; // Int
    source?: string | null; // String
  }
  IndicatorEntryOrderInput: { // input type
    column: NexusGenEnums['IndicatorEntryOrderBy']; // IndicatorEntryOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  IndicatorOrderInput: { // input type
    column: NexusGenEnums['IndicatorOrderBy']; // IndicatorOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  InitiativeArgs: { // input type
    id?: number | null; // Int
    ownerId?: number | null; // Int
    status?: NexusGenEnums['InitiativeStatus'] | null; // InitiativeStatus
    strategicObjectiveId?: number | null; // Int
    title?: string | null; // String
  }
  InitiativeOrderInput: { // input type
    column: NexusGenEnums['InitiativeOrderBy']; // InitiativeOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  NonConformityArgs: { // input type
    department?: string | null; // String
    id?: number | null; // Int
    ownerId?: number | null; // Int
    severity?: NexusGenEnums['NonConformitySeverity'] | null; // NonConformitySeverity
    status?: NexusGenEnums['NonConformityStatus'] | null; // NonConformityStatus
    title?: string | null; // String
  }
  NonConformityOrderInput: { // input type
    column: NexusGenEnums['NonConformityOrderBy']; // NonConformityOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  PageArgs: { // input type
    skip: number; // Int!
    take: number; // Int!
  }
  StrategicObjectiveArgs: { // input type
    id?: number | null; // Int
    ownerId?: number | null; // Int
    priority?: NexusGenEnums['StrategicObjectivePriority'] | null; // StrategicObjectivePriority
    status?: NexusGenEnums['StrategicObjectiveStatus'] | null; // StrategicObjectiveStatus
    title?: string | null; // String
  }
  StrategicObjectiveOrderInput: { // input type
    column: NexusGenEnums['StrategicObjectiveOrderBy']; // StrategicObjectiveOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  UserArgs: { // input type
    id?: number | null; // Int
    name?: string | null; // String
    username?: string | null; // String
  }
  UserInput: { // input type
    email: string; // String!
    name: string; // String!
    password: string; // String!
  }
  UserOrderInput: { // input type
    column: NexusGenEnums['UserOrderBy']; // UserOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
}

export interface NexusGenEnums {
  CorrectiveActionOrderBy: "CREATED_AT" | "DUE_AT" | "ID" | "NON_CONFORMITY_ID" | "STATUS"
  CorrectiveActionStatus: "CANCELLED" | "COMPLETED" | "IN_PROGRESS" | "OPEN"
  EffectivenessCheckOrderBy: "CHECKED_AT" | "CORRECTIVE_ACTION_ID" | "CREATED_AT" | "ID" | "RESULT"
  EffectivenessResult: "EFFECTIVE" | "INEFFECTIVE" | "NEEDS_MONITORING"
  EvidenceEntityType: "correctiveAction" | "indicator" | "initiative" | "nonConformity" | "strategicObjective"
  IndicatorEntryOrderBy: "COLLECTED_AT" | "CREATED_AT" | "ID" | "INDICATOR_ID" | "VALUE"
  IndicatorFrequency: "DAILY" | "MONTHLY" | "QUARTERLY" | "WEEKLY" | "YEARLY"
  IndicatorOrderBy: "CREATED_AT" | "FREQUENCY" | "ID" | "NAME" | "TARGET_VALUE"
  IndicatorTargetStatus: "BELOW_TARGET" | "NO_DATA" | "NO_TARGET" | "ON_TARGET"
  InitiativeOrderBy: "CREATED_AT" | "DUE_AT" | "ID" | "STATUS" | "STRATEGIC_OBJECTIVE_ID" | "TITLE"
  InitiativeStatus: "BLOCKED" | "COMPLETED" | "IN_PROGRESS" | "PLANNED"
  NonConformityOrderBy: "CREATED_AT" | "ID" | "OCCURRED_AT" | "SEVERITY" | "STATUS" | "TITLE"
  NonConformitySeverity: "CRITICAL" | "HIGH" | "LOW" | "MEDIUM"
  NonConformityStatus: "CLOSED" | "IN_PROGRESS" | "OPEN" | "RESOLVED"
  OrderDirection: "ASC" | "DESC"
  StrategicObjectiveOrderBy: "CREATED_AT" | "ENDS_AT" | "ID" | "PRIORITY" | "STARTS_AT" | "STATUS" | "TITLE"
  StrategicObjectivePriority: "CRITICAL" | "HIGH" | "LOW" | "MEDIUM"
  StrategicObjectiveStatus: "ACTIVE" | "ARCHIVED" | "COMPLETED" | "DRAFT"
  UserOrderBy: "ID" | "NAME" | "USERNAME"
  UserRole: "ADMIN" | "ANALYST" | "MANAGER" | "QUALITY_MANAGER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AuthResponse: { // root type
    tokens: NexusGenRootTypes['AuthTokens']; // AuthTokens!
    user: NexusGenRootTypes['User']; // User!
  }
  AuthTokens: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  CorrectiveAction: { // root type
    completedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    dueAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    nonConformityId: number; // Int!
    ownerId?: number | null; // Int
    status: NexusGenEnums['CorrectiveActionStatus']; // CorrectiveActionStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  CorrectiveActionList: { // root type
    nodes?: NexusGenRootTypes['CorrectiveAction'][] | null; // [CorrectiveAction!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  EffectivenessCheck: { // root type
    checkedAt: NexusGenScalars['DateTime']; // DateTime!
    correctiveActionId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    notes?: string | null; // String
    result: NexusGenEnums['EffectivenessResult']; // EffectivenessResult!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  EffectivenessCheckList: { // root type
    nodes?: NexusGenRootTypes['EffectivenessCheck'][] | null; // [EffectivenessCheck!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Evidence: { // root type
    contentType: string; // String!
    correctiveActionId?: number | null; // Int
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    deletedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    deletedById?: number | null; // Int
    fileName: string; // String!
    id: number; // Int!
    indicatorId?: number | null; // Int
    initiativeId?: number | null; // Int
    label?: string | null; // String
    nonConformityId?: number | null; // Int
    sizeBytes: number; // Int!
    strategicObjectiveId?: number | null; // Int
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById?: number | null; // Int
    uploadedById?: number | null; // Int
  }
  EvidenceList: { // root type
    nodes?: NexusGenRootTypes['Evidence'][] | null; // [Evidence!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Indicator: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    formula?: string | null; // String
    frequency: NexusGenEnums['IndicatorFrequency']; // IndicatorFrequency!
    id: number; // Int!
    name: string; // String!
    ownerId?: number | null; // Int
    targetValue?: number | null; // Float
    unit?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  IndicatorEntry: { // root type
    collectedAt: NexusGenScalars['DateTime']; // DateTime!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    indicatorId: number; // Int!
    notes?: string | null; // String
    source?: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    value: number; // Float!
  }
  IndicatorEntryList: { // root type
    nodes?: NexusGenRootTypes['IndicatorEntry'][] | null; // [IndicatorEntry!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  IndicatorList: { // root type
    nodes?: NexusGenRootTypes['Indicator'][] | null; // [Indicator!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Initiative: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    dueAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    ownerId?: number | null; // Int
    status: NexusGenEnums['InitiativeStatus']; // InitiativeStatus!
    strategicObjectiveId: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  InitiativeList: { // root type
    nodes?: NexusGenRootTypes['Initiative'][] | null; // [Initiative!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Mutation: {};
  NonConformity: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    department?: string | null; // String
    description?: string | null; // String
    id: number; // Int!
    occurredAt?: NexusGenScalars['DateTime'] | null; // DateTime
    ownerId?: number | null; // Int
    severity: NexusGenEnums['NonConformitySeverity']; // NonConformitySeverity!
    source?: string | null; // String
    status: NexusGenEnums['NonConformityStatus']; // NonConformityStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  NonConformityList: { // root type
    nodes?: NexusGenRootTypes['NonConformity'][] | null; // [NonConformity!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Pagination: { // root type
    hasMore: boolean; // Boolean!
    page: number; // Int!
    pageSize: number; // Int!
    totalCount: number; // Int!
  }
  Query: {};
  StrategicObjective: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    endsAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    ownerId?: number | null; // Int
    priority: NexusGenEnums['StrategicObjectivePriority']; // StrategicObjectivePriority!
    startsAt?: NexusGenScalars['DateTime'] | null; // DateTime
    status: NexusGenEnums['StrategicObjectiveStatus']; // StrategicObjectiveStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  StrategicObjectiveList: { // root type
    nodes?: NexusGenRootTypes['StrategicObjective'][] | null; // [StrategicObjective!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  User: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['UserRole']; // UserRole!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  UserList: { // root type
    nodes?: NexusGenRootTypes['User'][] | null; // [User!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthResponse: { // field return type
    tokens: NexusGenRootTypes['AuthTokens']; // AuthTokens!
    user: NexusGenRootTypes['User']; // User!
  }
  AuthTokens: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  CorrectiveAction: { // field return type
    completedAt: NexusGenScalars['DateTime'] | null; // DateTime
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    createdById: number | null; // Int
    createdByName: string | null; // String
    description: string | null; // String
    dueAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    nonConformityId: number; // Int!
    ownerId: number | null; // Int
    status: NexusGenEnums['CorrectiveActionStatus']; // CorrectiveActionStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById: number | null; // Int
    updatedByName: string | null; // String
  }
  CorrectiveActionList: { // field return type
    nodes: NexusGenRootTypes['CorrectiveAction'][] | null; // [CorrectiveAction!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  EffectivenessCheck: { // field return type
    checkedAt: NexusGenScalars['DateTime']; // DateTime!
    correctiveActionId: number; // Int!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    notes: string | null; // String
    result: NexusGenEnums['EffectivenessResult']; // EffectivenessResult!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  EffectivenessCheckList: { // field return type
    nodes: NexusGenRootTypes['EffectivenessCheck'][] | null; // [EffectivenessCheck!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Evidence: { // field return type
    contentType: string; // String!
    correctiveActionId: number | null; // Int
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    deletedAt: NexusGenScalars['DateTime'] | null; // DateTime
    deletedById: number | null; // Int
    deletedByName: string | null; // String
    downloadUrl: string; // String!
    fileName: string; // String!
    id: number; // Int!
    indicatorId: number | null; // Int
    initiativeId: number | null; // Int
    label: string | null; // String
    nonConformityId: number | null; // Int
    sizeBytes: number; // Int!
    strategicObjectiveId: number | null; // Int
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById: number | null; // Int
    updatedByName: string | null; // String
    uploadedById: number | null; // Int
    uploadedByName: string | null; // String
  }
  EvidenceList: { // field return type
    nodes: NexusGenRootTypes['Evidence'][] | null; // [Evidence!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Indicator: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    createdById: number | null; // Int
    createdByName: string | null; // String
    description: string | null; // String
    formula: string | null; // String
    frequency: NexusGenEnums['IndicatorFrequency']; // IndicatorFrequency!
    id: number; // Int!
    latestEntryCollectedAt: NexusGenScalars['DateTime'] | null; // DateTime
    latestEntryStatus: NexusGenEnums['IndicatorTargetStatus']; // IndicatorTargetStatus!
    latestEntryValue: number | null; // Float
    name: string; // String!
    ownerId: number | null; // Int
    targetValue: number | null; // Float
    unit: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById: number | null; // Int
    updatedByName: string | null; // String
  }
  IndicatorEntry: { // field return type
    collectedAt: NexusGenScalars['DateTime']; // DateTime!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: number; // Int!
    indicatorId: number; // Int!
    notes: string | null; // String
    source: string | null; // String
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    value: number; // Float!
  }
  IndicatorEntryList: { // field return type
    nodes: NexusGenRootTypes['IndicatorEntry'][] | null; // [IndicatorEntry!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  IndicatorList: { // field return type
    nodes: NexusGenRootTypes['Indicator'][] | null; // [Indicator!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Initiative: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    createdById: number | null; // Int
    createdByName: string | null; // String
    description: string | null; // String
    dueAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    ownerId: number | null; // Int
    status: NexusGenEnums['InitiativeStatus']; // InitiativeStatus!
    strategicObjectiveId: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById: number | null; // Int
    updatedByName: string | null; // String
  }
  InitiativeList: { // field return type
    nodes: NexusGenRootTypes['Initiative'][] | null; // [Initiative!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Mutation: { // field return type
    createCorrectiveAction: NexusGenRootTypes['CorrectiveAction'] | null; // CorrectiveAction
    createEffectivenessCheck: NexusGenRootTypes['EffectivenessCheck'] | null; // EffectivenessCheck
    createEvidence: NexusGenRootTypes['Evidence'] | null; // Evidence
    createIndicator: NexusGenRootTypes['Indicator'] | null; // Indicator
    createIndicatorEntry: NexusGenRootTypes['IndicatorEntry'] | null; // IndicatorEntry
    createInitiative: NexusGenRootTypes['Initiative'] | null; // Initiative
    createNonConformity: NexusGenRootTypes['NonConformity'] | null; // NonConformity
    createStrategicObjective: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    createUser: NexusGenRootTypes['User'] | null; // User
    deleteCorrectiveAction: NexusGenRootTypes['CorrectiveAction'] | null; // CorrectiveAction
    deleteEffectivenessCheck: NexusGenRootTypes['EffectivenessCheck'] | null; // EffectivenessCheck
    deleteEvidence: NexusGenRootTypes['Evidence'] | null; // Evidence
    deleteIndicator: NexusGenRootTypes['Indicator'] | null; // Indicator
    deleteIndicatorEntry: NexusGenRootTypes['IndicatorEntry'] | null; // IndicatorEntry
    deleteInitiative: NexusGenRootTypes['Initiative'] | null; // Initiative
    deleteNonConformity: NexusGenRootTypes['NonConformity'] | null; // NonConformity
    deleteStrategicObjective: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    deleteUser: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['AuthResponse']; // AuthResponse!
    logout: boolean; // Boolean!
    refreshToken: NexusGenRootTypes['AuthTokens']; // AuthTokens!
    register: NexusGenRootTypes['AuthResponse']; // AuthResponse!
    restoreEvidence: NexusGenRootTypes['Evidence'] | null; // Evidence
    updateCorrectiveAction: NexusGenRootTypes['CorrectiveAction'] | null; // CorrectiveAction
    updateEffectivenessCheck: NexusGenRootTypes['EffectivenessCheck'] | null; // EffectivenessCheck
    updateEvidence: NexusGenRootTypes['Evidence'] | null; // Evidence
    updateIndicator: NexusGenRootTypes['Indicator'] | null; // Indicator
    updateIndicatorEntry: NexusGenRootTypes['IndicatorEntry'] | null; // IndicatorEntry
    updateInitiative: NexusGenRootTypes['Initiative'] | null; // Initiative
    updateNonConformity: NexusGenRootTypes['NonConformity'] | null; // NonConformity
    updateStrategicObjective: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  NonConformity: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    createdById: number | null; // Int
    createdByName: string | null; // String
    department: string | null; // String
    description: string | null; // String
    id: number; // Int!
    occurredAt: NexusGenScalars['DateTime'] | null; // DateTime
    ownerId: number | null; // Int
    severity: NexusGenEnums['NonConformitySeverity']; // NonConformitySeverity!
    source: string | null; // String
    status: NexusGenEnums['NonConformityStatus']; // NonConformityStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById: number | null; // Int
    updatedByName: string | null; // String
  }
  NonConformityList: { // field return type
    nodes: NexusGenRootTypes['NonConformity'][] | null; // [NonConformity!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  Pagination: { // field return type
    hasMore: boolean; // Boolean!
    page: number; // Int!
    pageSize: number; // Int!
    totalCount: number; // Int!
  }
  Query: { // field return type
    correctiveActionGet: NexusGenRootTypes['CorrectiveAction'] | null; // CorrectiveAction
    correctiveActionLoad: NexusGenRootTypes['CorrectiveActionList'] | null; // CorrectiveActionList
    effectivenessCheckGet: NexusGenRootTypes['EffectivenessCheck'] | null; // EffectivenessCheck
    effectivenessCheckLoad: NexusGenRootTypes['EffectivenessCheckList'] | null; // EffectivenessCheckList
    evidenceLoad: NexusGenRootTypes['EvidenceList'] | null; // EvidenceList
    indicatorEntryGet: NexusGenRootTypes['IndicatorEntry'] | null; // IndicatorEntry
    indicatorEntryLoad: NexusGenRootTypes['IndicatorEntryList'] | null; // IndicatorEntryList
    indicatorGet: NexusGenRootTypes['Indicator'] | null; // Indicator
    indicatorLoad: NexusGenRootTypes['IndicatorList'] | null; // IndicatorList
    initiativeGet: NexusGenRootTypes['Initiative'] | null; // Initiative
    initiativeLoad: NexusGenRootTypes['InitiativeList'] | null; // InitiativeList
    me: NexusGenRootTypes['User'] | null; // User
    nonConformityGet: NexusGenRootTypes['NonConformity'] | null; // NonConformity
    nonConformityLoad: NexusGenRootTypes['NonConformityList'] | null; // NonConformityList
    strategicObjectiveGet: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    strategicObjectiveLoad: NexusGenRootTypes['StrategicObjectiveList'] | null; // StrategicObjectiveList
    userGet: NexusGenRootTypes['User'] | null; // User
    userLoad: NexusGenRootTypes['UserList'] | null; // UserList
  }
  StrategicObjective: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    createdById: number | null; // Int
    createdByName: string | null; // String
    description: string | null; // String
    endsAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    ownerId: number | null; // Int
    priority: NexusGenEnums['StrategicObjectivePriority']; // StrategicObjectivePriority!
    startsAt: NexusGenScalars['DateTime'] | null; // DateTime
    status: NexusGenEnums['StrategicObjectiveStatus']; // StrategicObjectiveStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    updatedById: number | null; // Int
    updatedByName: string | null; // String
  }
  StrategicObjectiveList: { // field return type
    nodes: NexusGenRootTypes['StrategicObjective'][] | null; // [StrategicObjective!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['UserRole']; // UserRole!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  UserList: { // field return type
    nodes: NexusGenRootTypes['User'][] | null; // [User!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
}

export interface NexusGenFieldTypeNames {
  AuthResponse: { // field return type name
    tokens: 'AuthTokens'
    user: 'User'
  }
  AuthTokens: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
  }
  CorrectiveAction: { // field return type name
    completedAt: 'DateTime'
    createdAt: 'DateTime'
    createdById: 'Int'
    createdByName: 'String'
    description: 'String'
    dueAt: 'DateTime'
    id: 'Int'
    nonConformityId: 'Int'
    ownerId: 'Int'
    status: 'CorrectiveActionStatus'
    title: 'String'
    updatedAt: 'DateTime'
    updatedById: 'Int'
    updatedByName: 'String'
  }
  CorrectiveActionList: { // field return type name
    nodes: 'CorrectiveAction'
    pagination: 'Pagination'
  }
  EffectivenessCheck: { // field return type name
    checkedAt: 'DateTime'
    correctiveActionId: 'Int'
    createdAt: 'DateTime'
    id: 'Int'
    notes: 'String'
    result: 'EffectivenessResult'
    updatedAt: 'DateTime'
  }
  EffectivenessCheckList: { // field return type name
    nodes: 'EffectivenessCheck'
    pagination: 'Pagination'
  }
  Evidence: { // field return type name
    contentType: 'String'
    correctiveActionId: 'Int'
    createdAt: 'DateTime'
    deletedAt: 'DateTime'
    deletedById: 'Int'
    deletedByName: 'String'
    downloadUrl: 'String'
    fileName: 'String'
    id: 'Int'
    indicatorId: 'Int'
    initiativeId: 'Int'
    label: 'String'
    nonConformityId: 'Int'
    sizeBytes: 'Int'
    strategicObjectiveId: 'Int'
    updatedAt: 'DateTime'
    updatedById: 'Int'
    updatedByName: 'String'
    uploadedById: 'Int'
    uploadedByName: 'String'
  }
  EvidenceList: { // field return type name
    nodes: 'Evidence'
    pagination: 'Pagination'
  }
  Indicator: { // field return type name
    createdAt: 'DateTime'
    createdById: 'Int'
    createdByName: 'String'
    description: 'String'
    formula: 'String'
    frequency: 'IndicatorFrequency'
    id: 'Int'
    latestEntryCollectedAt: 'DateTime'
    latestEntryStatus: 'IndicatorTargetStatus'
    latestEntryValue: 'Float'
    name: 'String'
    ownerId: 'Int'
    targetValue: 'Float'
    unit: 'String'
    updatedAt: 'DateTime'
    updatedById: 'Int'
    updatedByName: 'String'
  }
  IndicatorEntry: { // field return type name
    collectedAt: 'DateTime'
    createdAt: 'DateTime'
    id: 'Int'
    indicatorId: 'Int'
    notes: 'String'
    source: 'String'
    updatedAt: 'DateTime'
    value: 'Float'
  }
  IndicatorEntryList: { // field return type name
    nodes: 'IndicatorEntry'
    pagination: 'Pagination'
  }
  IndicatorList: { // field return type name
    nodes: 'Indicator'
    pagination: 'Pagination'
  }
  Initiative: { // field return type name
    createdAt: 'DateTime'
    createdById: 'Int'
    createdByName: 'String'
    description: 'String'
    dueAt: 'DateTime'
    id: 'Int'
    ownerId: 'Int'
    status: 'InitiativeStatus'
    strategicObjectiveId: 'Int'
    title: 'String'
    updatedAt: 'DateTime'
    updatedById: 'Int'
    updatedByName: 'String'
  }
  InitiativeList: { // field return type name
    nodes: 'Initiative'
    pagination: 'Pagination'
  }
  Mutation: { // field return type name
    createCorrectiveAction: 'CorrectiveAction'
    createEffectivenessCheck: 'EffectivenessCheck'
    createEvidence: 'Evidence'
    createIndicator: 'Indicator'
    createIndicatorEntry: 'IndicatorEntry'
    createInitiative: 'Initiative'
    createNonConformity: 'NonConformity'
    createStrategicObjective: 'StrategicObjective'
    createUser: 'User'
    deleteCorrectiveAction: 'CorrectiveAction'
    deleteEffectivenessCheck: 'EffectivenessCheck'
    deleteEvidence: 'Evidence'
    deleteIndicator: 'Indicator'
    deleteIndicatorEntry: 'IndicatorEntry'
    deleteInitiative: 'Initiative'
    deleteNonConformity: 'NonConformity'
    deleteStrategicObjective: 'StrategicObjective'
    deleteUser: 'User'
    login: 'AuthResponse'
    logout: 'Boolean'
    refreshToken: 'AuthTokens'
    register: 'AuthResponse'
    restoreEvidence: 'Evidence'
    updateCorrectiveAction: 'CorrectiveAction'
    updateEffectivenessCheck: 'EffectivenessCheck'
    updateEvidence: 'Evidence'
    updateIndicator: 'Indicator'
    updateIndicatorEntry: 'IndicatorEntry'
    updateInitiative: 'Initiative'
    updateNonConformity: 'NonConformity'
    updateStrategicObjective: 'StrategicObjective'
    updateUser: 'User'
  }
  NonConformity: { // field return type name
    createdAt: 'DateTime'
    createdById: 'Int'
    createdByName: 'String'
    department: 'String'
    description: 'String'
    id: 'Int'
    occurredAt: 'DateTime'
    ownerId: 'Int'
    severity: 'NonConformitySeverity'
    source: 'String'
    status: 'NonConformityStatus'
    title: 'String'
    updatedAt: 'DateTime'
    updatedById: 'Int'
    updatedByName: 'String'
  }
  NonConformityList: { // field return type name
    nodes: 'NonConformity'
    pagination: 'Pagination'
  }
  Pagination: { // field return type name
    hasMore: 'Boolean'
    page: 'Int'
    pageSize: 'Int'
    totalCount: 'Int'
  }
  Query: { // field return type name
    correctiveActionGet: 'CorrectiveAction'
    correctiveActionLoad: 'CorrectiveActionList'
    effectivenessCheckGet: 'EffectivenessCheck'
    effectivenessCheckLoad: 'EffectivenessCheckList'
    evidenceLoad: 'EvidenceList'
    indicatorEntryGet: 'IndicatorEntry'
    indicatorEntryLoad: 'IndicatorEntryList'
    indicatorGet: 'Indicator'
    indicatorLoad: 'IndicatorList'
    initiativeGet: 'Initiative'
    initiativeLoad: 'InitiativeList'
    me: 'User'
    nonConformityGet: 'NonConformity'
    nonConformityLoad: 'NonConformityList'
    strategicObjectiveGet: 'StrategicObjective'
    strategicObjectiveLoad: 'StrategicObjectiveList'
    userGet: 'User'
    userLoad: 'UserList'
  }
  StrategicObjective: { // field return type name
    createdAt: 'DateTime'
    createdById: 'Int'
    createdByName: 'String'
    description: 'String'
    endsAt: 'DateTime'
    id: 'Int'
    ownerId: 'Int'
    priority: 'StrategicObjectivePriority'
    startsAt: 'DateTime'
    status: 'StrategicObjectiveStatus'
    title: 'String'
    updatedAt: 'DateTime'
    updatedById: 'Int'
    updatedByName: 'String'
  }
  StrategicObjectiveList: { // field return type name
    nodes: 'StrategicObjective'
    pagination: 'Pagination'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'Int'
    name: 'String'
    role: 'UserRole'
    updatedAt: 'DateTime'
  }
  UserList: { // field return type name
    nodes: 'User'
    pagination: 'Pagination'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createCorrectiveAction: { // args
      completedAt?: NexusGenScalars['DateTime'] | null; // DateTime
      description?: string | null; // String
      dueAt?: NexusGenScalars['DateTime'] | null; // DateTime
      nonConformityId: number; // Int!
      ownerId?: number | null; // Int
      status?: NexusGenEnums['CorrectiveActionStatus'] | null; // CorrectiveActionStatus
      title: string; // String!
    }
    createEffectivenessCheck: { // args
      checkedAt?: NexusGenScalars['DateTime'] | null; // DateTime
      correctiveActionId: number; // Int!
      notes?: string | null; // String
      result: NexusGenEnums['EffectivenessResult']; // EffectivenessResult!
    }
    createEvidence: { // args
      base64Data: string; // String!
      contentType: string; // String!
      entityId: number; // Int!
      entityType: NexusGenEnums['EvidenceEntityType']; // EvidenceEntityType!
      fileName: string; // String!
      label?: string | null; // String
    }
    createIndicator: { // args
      description?: string | null; // String
      formula?: string | null; // String
      frequency?: NexusGenEnums['IndicatorFrequency'] | null; // IndicatorFrequency
      name: string; // String!
      ownerId?: number | null; // Int
      targetValue?: number | null; // Float
      unit?: string | null; // String
    }
    createIndicatorEntry: { // args
      collectedAt?: NexusGenScalars['DateTime'] | null; // DateTime
      indicatorId: number; // Int!
      notes?: string | null; // String
      source?: string | null; // String
      value: number; // Float!
    }
    createInitiative: { // args
      description?: string | null; // String
      dueAt?: NexusGenScalars['DateTime'] | null; // DateTime
      ownerId?: number | null; // Int
      status?: NexusGenEnums['InitiativeStatus'] | null; // InitiativeStatus
      strategicObjectiveId: number; // Int!
      title: string; // String!
    }
    createNonConformity: { // args
      department?: string | null; // String
      description?: string | null; // String
      occurredAt?: NexusGenScalars['DateTime'] | null; // DateTime
      ownerId?: number | null; // Int
      severity?: NexusGenEnums['NonConformitySeverity'] | null; // NonConformitySeverity
      source?: string | null; // String
      status?: NexusGenEnums['NonConformityStatus'] | null; // NonConformityStatus
      title: string; // String!
    }
    createStrategicObjective: { // args
      description?: string | null; // String
      endsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      ownerId?: number | null; // Int
      priority?: NexusGenEnums['StrategicObjectivePriority'] | null; // StrategicObjectivePriority
      startsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      status?: NexusGenEnums['StrategicObjectiveStatus'] | null; // StrategicObjectiveStatus
      title: string; // String!
    }
    createUser: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    deleteCorrectiveAction: { // args
      id: number; // Int!
    }
    deleteEffectivenessCheck: { // args
      id: number; // Int!
    }
    deleteEvidence: { // args
      id: number; // Int!
    }
    deleteIndicator: { // args
      id: number; // Int!
    }
    deleteIndicatorEntry: { // args
      id: number; // Int!
    }
    deleteInitiative: { // args
      id: number; // Int!
    }
    deleteNonConformity: { // args
      id: number; // Int!
    }
    deleteStrategicObjective: { // args
      id: number; // Int!
    }
    deleteUser: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    refreshToken: { // args
      refreshToken: string; // String!
    }
    register: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    restoreEvidence: { // args
      id: number; // Int!
    }
    updateCorrectiveAction: { // args
      completedAt?: NexusGenScalars['DateTime'] | null; // DateTime
      description?: string | null; // String
      dueAt?: NexusGenScalars['DateTime'] | null; // DateTime
      id: number; // Int!
      nonConformityId?: number | null; // Int
      ownerId?: number | null; // Int
      status?: NexusGenEnums['CorrectiveActionStatus'] | null; // CorrectiveActionStatus
      title?: string | null; // String
    }
    updateEffectivenessCheck: { // args
      checkedAt?: NexusGenScalars['DateTime'] | null; // DateTime
      correctiveActionId?: number | null; // Int
      id: number; // Int!
      notes?: string | null; // String
      result?: NexusGenEnums['EffectivenessResult'] | null; // EffectivenessResult
    }
    updateEvidence: { // args
      id: number; // Int!
      label?: string | null; // String
    }
    updateIndicator: { // args
      description?: string | null; // String
      formula?: string | null; // String
      frequency?: NexusGenEnums['IndicatorFrequency'] | null; // IndicatorFrequency
      id: number; // Int!
      name?: string | null; // String
      ownerId?: number | null; // Int
      targetValue?: number | null; // Float
      unit?: string | null; // String
    }
    updateIndicatorEntry: { // args
      collectedAt?: NexusGenScalars['DateTime'] | null; // DateTime
      id: number; // Int!
      indicatorId?: number | null; // Int
      notes?: string | null; // String
      source?: string | null; // String
      value?: number | null; // Float
    }
    updateInitiative: { // args
      description?: string | null; // String
      dueAt?: NexusGenScalars['DateTime'] | null; // DateTime
      id: number; // Int!
      ownerId?: number | null; // Int
      status?: NexusGenEnums['InitiativeStatus'] | null; // InitiativeStatus
      strategicObjectiveId?: number | null; // Int
      title?: string | null; // String
    }
    updateNonConformity: { // args
      department?: string | null; // String
      description?: string | null; // String
      id: number; // Int!
      occurredAt?: NexusGenScalars['DateTime'] | null; // DateTime
      ownerId?: number | null; // Int
      severity?: NexusGenEnums['NonConformitySeverity'] | null; // NonConformitySeverity
      source?: string | null; // String
      status?: NexusGenEnums['NonConformityStatus'] | null; // NonConformityStatus
      title?: string | null; // String
    }
    updateStrategicObjective: { // args
      description?: string | null; // String
      endsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      id: number; // Int!
      ownerId?: number | null; // Int
      priority?: NexusGenEnums['StrategicObjectivePriority'] | null; // StrategicObjectivePriority
      startsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      status?: NexusGenEnums['StrategicObjectiveStatus'] | null; // StrategicObjectiveStatus
      title?: string | null; // String
    }
    updateUser: { // args
      email?: string | null; // String
      id: number; // Int!
      name?: string | null; // String
    }
  }
  Query: {
    correctiveActionGet: { // args
      id: number; // Int!
    }
    correctiveActionLoad: { // args
      filterArgs?: NexusGenInputs['CorrectiveActionArgs'] | null; // CorrectiveActionArgs
      order?: NexusGenInputs['CorrectiveActionOrderInput'] | null; // CorrectiveActionOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    effectivenessCheckGet: { // args
      id: number; // Int!
    }
    effectivenessCheckLoad: { // args
      filterArgs?: NexusGenInputs['EffectivenessCheckArgs'] | null; // EffectivenessCheckArgs
      order?: NexusGenInputs['EffectivenessCheckOrderInput'] | null; // EffectivenessCheckOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    evidenceLoad: { // args
      filterArgs?: NexusGenInputs['EvidenceArgs'] | null; // EvidenceArgs
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    indicatorEntryGet: { // args
      id: number; // Int!
    }
    indicatorEntryLoad: { // args
      filterArgs?: NexusGenInputs['IndicatorEntryArgs'] | null; // IndicatorEntryArgs
      order?: NexusGenInputs['IndicatorEntryOrderInput'] | null; // IndicatorEntryOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    indicatorGet: { // args
      id: number; // Int!
    }
    indicatorLoad: { // args
      filterArgs?: NexusGenInputs['IndicatorArgs'] | null; // IndicatorArgs
      order?: NexusGenInputs['IndicatorOrderInput'] | null; // IndicatorOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    initiativeGet: { // args
      id?: number | null; // Int
    }
    initiativeLoad: { // args
      filterArgs?: NexusGenInputs['InitiativeArgs'] | null; // InitiativeArgs
      order?: NexusGenInputs['InitiativeOrderInput'] | null; // InitiativeOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    nonConformityGet: { // args
      id: number; // Int!
    }
    nonConformityLoad: { // args
      filterArgs?: NexusGenInputs['NonConformityArgs'] | null; // NonConformityArgs
      order?: NexusGenInputs['NonConformityOrderInput'] | null; // NonConformityOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    strategicObjectiveGet: { // args
      id: number; // Int!
    }
    strategicObjectiveLoad: { // args
      filterArgs?: NexusGenInputs['StrategicObjectiveArgs'] | null; // StrategicObjectiveArgs
      order?: NexusGenInputs['StrategicObjectiveOrderInput'] | null; // StrategicObjectiveOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    userGet: { // args
      id: number; // Int!
    }
    userLoad: { // args
      filterArgs?: NexusGenInputs['UserArgs'] | null; // UserArgs
      order?: NexusGenInputs['UserOrderInput'] | null; // UserOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}