/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../types"
import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Date custom scalar type
     */
    dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  PageArgs: { // input type
    skip: number; // Int!
    take: number; // Int!
  }
  StrategicObjectiveArgs: { // input type
    id?: number | null; // Int
    ownerId?: number | null; // Int
    priority?: NexusGenEnums['StrategicObjectivePriority'] | null; // StrategicObjectivePriority
    status?: NexusGenEnums['StrategicObjectiveStatus'] | null; // StrategicObjectiveStatus
    title?: string | null; // String
  }
  StrategicObjectiveOrderInput: { // input type
    column: NexusGenEnums['StrategicObjectiveOrderBy']; // StrategicObjectiveOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
  UserArgs: { // input type
    id?: number | null; // Int
    name?: string | null; // String
    username?: string | null; // String
  }
  UserInput: { // input type
    email: string; // String!
    name: string; // String!
    password: string; // String!
  }
  UserOrderInput: { // input type
    column: NexusGenEnums['UserOrderBy']; // UserOrderBy!
    direction: NexusGenEnums['OrderDirection']; // OrderDirection!
  }
}

export interface NexusGenEnums {
  OrderDirection: "ASC" | "DESC"
  StrategicObjectiveOrderBy: "CREATED_AT" | "ENDS_AT" | "ID" | "PRIORITY" | "STARTS_AT" | "STATUS" | "TITLE"
  StrategicObjectivePriority: "CRITICAL" | "HIGH" | "LOW" | "MEDIUM"
  StrategicObjectiveStatus: "ACTIVE" | "ARCHIVED" | "COMPLETED" | "DRAFT"
  UserOrderBy: "ID" | "NAME" | "USERNAME"
  UserRole: "ADMIN" | "ANALYST" | "MANAGER" | "QUALITY_MANAGER"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  AuthResponse: { // root type
    tokens: NexusGenRootTypes['AuthTokens']; // AuthTokens!
    user: NexusGenRootTypes['User']; // User!
  }
  AuthTokens: { // root type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  Mutation: {};
  Pagination: { // root type
    hasMore: boolean; // Boolean!
    page: number; // Int!
    pageSize: number; // Int!
    totalCount: number; // Int!
  }
  Query: {};
  StrategicObjective: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    endsAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    ownerId?: number | null; // Int
    priority: NexusGenEnums['StrategicObjectivePriority']; // StrategicObjectivePriority!
    startsAt?: NexusGenScalars['DateTime'] | null; // DateTime
    status: NexusGenEnums['StrategicObjectiveStatus']; // StrategicObjectiveStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  StrategicObjectiveList: { // root type
    nodes?: NexusGenRootTypes['StrategicObjective'][] | null; // [StrategicObjective!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  User: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['UserRole']; // UserRole!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  UserList: { // root type
    nodes?: NexusGenRootTypes['User'][] | null; // [User!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AuthResponse: { // field return type
    tokens: NexusGenRootTypes['AuthTokens']; // AuthTokens!
    user: NexusGenRootTypes['User']; // User!
  }
  AuthTokens: { // field return type
    accessToken: string; // String!
    refreshToken: string; // String!
  }
  Mutation: { // field return type
    createStrategicObjective: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    createUser: NexusGenRootTypes['User'] | null; // User
    deleteStrategicObjective: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    deleteUser: NexusGenRootTypes['User'] | null; // User
    login: NexusGenRootTypes['AuthResponse']; // AuthResponse!
    logout: boolean; // Boolean!
    refreshToken: NexusGenRootTypes['AuthTokens']; // AuthTokens!
    register: NexusGenRootTypes['AuthResponse']; // AuthResponse!
    updateStrategicObjective: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    updateUser: NexusGenRootTypes['User'] | null; // User
  }
  Pagination: { // field return type
    hasMore: boolean; // Boolean!
    page: number; // Int!
    pageSize: number; // Int!
    totalCount: number; // Int!
  }
  Query: { // field return type
    me: NexusGenRootTypes['User'] | null; // User
    strategicObjectiveGet: NexusGenRootTypes['StrategicObjective'] | null; // StrategicObjective
    strategicObjectiveLoad: NexusGenRootTypes['StrategicObjectiveList'] | null; // StrategicObjectiveList
    userGet: NexusGenRootTypes['User'] | null; // User
    userLoad: NexusGenRootTypes['UserList'] | null; // UserList
  }
  StrategicObjective: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    endsAt: NexusGenScalars['DateTime'] | null; // DateTime
    id: number; // Int!
    ownerId: number | null; // Int
    priority: NexusGenEnums['StrategicObjectivePriority']; // StrategicObjectivePriority!
    startsAt: NexusGenScalars['DateTime'] | null; // DateTime
    status: NexusGenEnums['StrategicObjectiveStatus']; // StrategicObjectiveStatus!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  StrategicObjectiveList: { // field return type
    nodes: NexusGenRootTypes['StrategicObjective'][] | null; // [StrategicObjective!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    role: NexusGenEnums['UserRole']; // UserRole!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  UserList: { // field return type
    nodes: NexusGenRootTypes['User'][] | null; // [User!]
    pagination: NexusGenRootTypes['Pagination']; // Pagination!
  }
}

export interface NexusGenFieldTypeNames {
  AuthResponse: { // field return type name
    tokens: 'AuthTokens'
    user: 'User'
  }
  AuthTokens: { // field return type name
    accessToken: 'String'
    refreshToken: 'String'
  }
  Mutation: { // field return type name
    createStrategicObjective: 'StrategicObjective'
    createUser: 'User'
    deleteStrategicObjective: 'StrategicObjective'
    deleteUser: 'User'
    login: 'AuthResponse'
    logout: 'Boolean'
    refreshToken: 'AuthTokens'
    register: 'AuthResponse'
    updateStrategicObjective: 'StrategicObjective'
    updateUser: 'User'
  }
  Pagination: { // field return type name
    hasMore: 'Boolean'
    page: 'Int'
    pageSize: 'Int'
    totalCount: 'Int'
  }
  Query: { // field return type name
    me: 'User'
    strategicObjectiveGet: 'StrategicObjective'
    strategicObjectiveLoad: 'StrategicObjectiveList'
    userGet: 'User'
    userLoad: 'UserList'
  }
  StrategicObjective: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    endsAt: 'DateTime'
    id: 'Int'
    ownerId: 'Int'
    priority: 'StrategicObjectivePriority'
    startsAt: 'DateTime'
    status: 'StrategicObjectiveStatus'
    title: 'String'
    updatedAt: 'DateTime'
  }
  StrategicObjectiveList: { // field return type name
    nodes: 'StrategicObjective'
    pagination: 'Pagination'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    id: 'Int'
    name: 'String'
    role: 'UserRole'
    updatedAt: 'DateTime'
  }
  UserList: { // field return type name
    nodes: 'User'
    pagination: 'Pagination'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createStrategicObjective: { // args
      description?: string | null; // String
      endsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      ownerId?: number | null; // Int
      priority?: NexusGenEnums['StrategicObjectivePriority'] | null; // StrategicObjectivePriority
      startsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      status?: NexusGenEnums['StrategicObjectiveStatus'] | null; // StrategicObjectiveStatus
      title: string; // String!
    }
    createUser: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    deleteStrategicObjective: { // args
      id: number; // Int!
    }
    deleteUser: { // args
      id: number; // Int!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
    refreshToken: { // args
      refreshToken: string; // String!
    }
    register: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
    }
    updateStrategicObjective: { // args
      description?: string | null; // String
      endsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      id: number; // Int!
      ownerId?: number | null; // Int
      priority?: NexusGenEnums['StrategicObjectivePriority'] | null; // StrategicObjectivePriority
      startsAt?: NexusGenScalars['DateTime'] | null; // DateTime
      status?: NexusGenEnums['StrategicObjectiveStatus'] | null; // StrategicObjectiveStatus
      title?: string | null; // String
    }
    updateUser: { // args
      email?: string | null; // String
      id: number; // Int!
      name?: string | null; // String
    }
  }
  Query: {
    strategicObjectiveGet: { // args
      id: number; // Int!
    }
    strategicObjectiveLoad: { // args
      filterArgs?: NexusGenInputs['StrategicObjectiveArgs'] | null; // StrategicObjectiveArgs
      order?: NexusGenInputs['StrategicObjectiveOrderInput'] | null; // StrategicObjectiveOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
    userGet: { // args
      id: number; // Int!
    }
    userLoad: { // args
      filterArgs?: NexusGenInputs['UserArgs'] | null; // UserArgs
      order?: NexusGenInputs['UserOrderInput'] | null; // UserOrderInput
      pageArgs?: NexusGenInputs['PageArgs'] | null; // PageArgs
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}